### ISSUE TITLE
Yozh is no longer recognized as a Drive

### ISSUE THREAD

**Issue by QuadNuker29** [shurik179/yozh#1]
Hey, this is David R from Sigma.
Before, when I would plug the robot into the computer, it would get recognized as a storage drive and pop up in files. Now it just draws power but doesn't connect. How should I fix this?
Contact me at quadnuker29@gmail.com

**Comment by shurik179** [comment]
Hi, David!
Yes, we had multiple problems with CIRCUITPY drive disappearing, not sure why. 
I wrote some ways to fix this in this google doc: 
https://docs.google.com/document/d/1C4rf-fTO2_A6d-Higqi1a8Bx7qhjb13ecvsjiudTvfw/edit?usp=sharing
(see page 2)

**Comment by QuadNuker29** [comment]
Thanks!

**Comment by shurik179** [comment]
closed
